In [576]:
import pandas as pd
import numpy as np

In [575]:
data = pd.read_csv('train.csv')
data = data.dropna()
data.head(5)

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,...,wtd_mean_Valence,gmean_Valence,wtd_gmean_Valence,entropy_Valence,wtd_entropy_Valence,range_Valence,wtd_range_Valence,std_Valence,wtd_std_Valence,critical_temp
0,4,88.944468,57.862692,66.361592,36.116612,1.181795,1.062396,122.90607,31.794921,51.968828,...,2.257143,2.213364,2.219783,1.368922,1.066221,1,1.085714,0.433013,0.437059,29.0
1,5,92.729214,58.518416,73.132787,36.396602,1.449309,1.057755,122.90607,36.161939,47.094633,...,2.257143,1.888175,2.210679,1.557113,1.047221,2,1.128571,0.632456,0.468606,26.0
2,4,88.944468,57.885242,66.361592,36.122509,1.181795,0.975980,122.90607,35.741099,51.968828,...,2.271429,2.213364,2.232679,1.368922,1.029175,1,1.114286,0.433013,0.444697,19.0
3,4,88.944468,57.873967,66.361592,36.119560,1.181795,1.022291,122.90607,33.768010,51.968828,...,2.264286,2.213364,2.226222,1.368922,1.048834,1,1.100000,0.433013,0.440952,22.0
4,4,88.944468,57.840143,66.361592,36.110716,1.181795,1.129224,122.90607,27.848743,51.968828,...,2.242857,2.213364,2.206963,1.368922,1.096052,1,1.057143,0.433013,0.428809,23.0

In [553]:
from sklearn.model_selection import train_test_split

X = data.iloc[:,0:80]
y = data.iloc[:,80:83]

from sklearn.preprocessing import LabelEncoder
y_t = LabelEncoder()
y['material_change'] = y_t.fit(y['material'])
y['material_change'] = y_t.transform(y['material'])
y = y.drop(['material'],axis=1)

In [569]:
from sklearn.linear_model import TheilSenRegressor
from sklearn.multioutput import MultiOutputRegressor
for i in range(0,1):
  X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.18,shuffle=True,random_state=415)
  #CREATING MODEL
  models = TheilSenRegressor(fit_intercept=True,
                             copy_X=True,
                             max_subpopulation=5904,
                             n_subsamples=None,
                             max_iter=150,tol=0.0001,
                             random_state=None,
                             verbose=1,
                             n_jobs=-1)
  models = MultiOutputRegressor(estimator=models)
  models.fit(X_train,y_train)
  #SAVE MODEL
  import joblib
  filename = 'emirhan_model.sav'
  joblib.dump(models, filename)
  #ACCURACY
  print(models.score(X_test,y_test))
  #LOAD MODEL
  models = joblib.load(filename)

In [572]:
models.score(X_test,y_test)

0.945097924903055

In [562]:
forexamplee = [92.729214,58.51841614,73.13278722,36.39660203,1.449309193,1.057755123,122.90607,36.161939,47.09463317,53.97986965,766.44,1010.612857,720.6055105,938.7454125,1.544144543,0.807078215,810.6,743.1642857,290.1830291,354.9635112,161.2,104.9714286,141.4652148,84.37016696,1.50832754,1.204114798,205,50.57142857,67.32131906,68.00881696,5821.4858,3021.016571,1237.09508,54.09571826,1.314442185,0.914802177,10488.571,1667.383429,3767.403176,3632.649185,90.89,112.3164286,69.83331461,101.1663977,1.427996553,0.838666466,127.05,81.20785714,49.43816744,41.6676208,7.7844,3.796857143,4.403790498,1.035251116,1.37497728,1.073093846,12.878,1.595714286,4.473362655,4.60300006,172.205316,61.37233143,16.06422788,0.619734632,0.847404163,0.567706108,429.97342,51.41338286,198.5546003,139.6309224,2,2.257142857,1.888175023,2.210679409,1.557113098,1.047221368,2,1.128571429,0.632455532,0.46860627]
forexamplee_answer = ["Real: 26",
                      "Prediction: 27",
                      "Real: 5",
                      "Prediction : 5",
                      "Real: Ba0.1La1.9Ag0.1Cu0.9O4",
                      "Prediction: Ba0.1La1.9Ag0.1Cu0.9O4"]
forexamplee_answer

['Real: 26',
 'Prediction: 27',
 'Real: 5',
 'Prediction : 5',
 'Real: Ba0.1La1.9Ag0.1Cu0.9O4',
 'Prediction: Ba0.1La1.9Ag0.1Cu0.9O4']

In [567]:
prediction = models.predict([forexamplee])
print("Temp: ",int(prediction[0][0]))
print("Number: ",int(prediction[0][1]))
print("Molecule: ", y_t.inverse_transform(np.array(int(prediction[0][2])).reshape(1,-1)))
print(""" 
This artificial intelligence software was developed by Emirhan BULUT. 
It is open sourced for Chemistry Scientists with 95% accuracy.
Artificial Intelligence determines the Critical Temperature, 
Number of Molecules and Molecular skeleton (shape) by detecting the properties of superconductors.



""")

Temp:  27
Number:  5
Molecule:  ['Ba0.1La1.9Ag0.1Cu0.9O4']

This artificial intelligence software was developed by Emirhan BULUT.
It is open sourced for Chemistry Scientists with 95% accuracy.
Artificial Intelligence determines the Critical Temperature,
Number of Molecules and Molecular skeleton (shape) by detecting the properties of superconductors.

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but TheilSenRegressor was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but TheilSenRegressor was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but TheilSenRegressor was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:154: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)